---
title: "Neural Network Model"
author: "Elizabeth Yenni"
date: "5/2/2022"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# CORRECT DIRECTORY BELOW, should be a folder containing the train and test folders.
my_directory = ""
knitr::opts_knit$set(root.dir = my_directory)
```

```{r, echo=FALSE, message=FALSE}
library(tidyverse)# metapackage of all tidyverse packages
library(tidyr)
library(png)  
library(grid)
library(jpeg)
library(imager)
library(ggplot2)
library(magick)
library(tensorflow)
library(ggplot2)
library(abind)
library(keras)
library(tensorflow)
```

# Pre-processing the Data

```{r}
# List of produce item names
label_list <- dir("train/")
```

```{r}
# Store each image as vector of length 28x28=784 in train_images
dir_train <- dir("train/")
set <- "train/"
files <-  list.files(set, pattern = ".", all.files = FALSE, recursive = TRUE, full.names = TRUE)
train_labels <- c()
train_images <- array(data = rep(0,28*28), dim = c(1,28,28))

for (folder in dir_train) {
  folder_path <- paste(set, folder, sep="")
  for (file in list.files(folder_path)) {
    if (and(folder=="beetroot", file=="Image_75.jpg") 
        || and(folder=="carrot", file=="Image_78.jpg") 
        || and(folder=="chilli pepper", file=="Image_20.jpg") 
        || and(folder=="chilli pepper", file=="Image_36.jpg") 
        || and(folder=="cucumber", file=="Image_58.jpg") 
        || and(folder=="eggplant", file=="Image_56.jpg") 
        || and(folder=="jalepeno", file=="Image_38.jpg") 
        || and(folder=="jalepeno", file=="Image_61.jpg") 
        || and(folder=="onion", file=="Image_52.jpg") 
        || and(folder=="tomato", file=="Image_43.jpg") 
        || and(folder=="tomato", file=="Image_81.jpg") 
        || and(folder=="turnip", file=="Image_43.jpg")) {
      next
    }
    # Getting vector of labels
    img_label <- file
    img_path <- paste(folder_path,"/", img_label, sep="")
    train_labels <- c(train_labels, folder)
    
    # vectorize images as 28x28
    img <- image_read(img_path)
    thmb <- image_scale(img, "28x28!")# resize(jpg, size_x=28, size_y=28)
    
    png <- image_convert(thmb, format = "png", colorspace = "gray")
    raster <- as.raster(png)
    v <- as.vector(raster)
    
    v_num <- c()
    for (i in 1:784) {
      rgb.array <- col2rgb(v[i])
      v_num <- c(v_num, rgb.array[1])
    }
    v_num <- matrix(v_num,nrow=28,byrow=TRUE)
    train_images <- abind(train_images, v_num/255, along = 1)
  }
}

train_images <- train_images[-1,,]
dim(train_images)
length(train_labels)
```

```{r}
# Store each image as vector of length 28x28=784 in test_images
dir_test <- dir("test/")
set <- "test/"
files <-  list.files(set, pattern = ".", all.files = FALSE, recursive = TRUE, full.names = TRUE)
test_labels <- c()
test_images <- array(data = rep(0,28*28), dim = c(1,28,28))

for (folder in dir_test) {
  folder_path <- paste(set, folder, sep="")
  for (file in list.files(folder_path)) {
    if (and(folder=="beetroot", file=="Image_75.jpg") 
        || and(folder=="carrot", file=="Image_78.jpg") 
        || and(folder=="chilli pepper", file=="Image_20.jpg") 
        || and(folder=="chilli pepper", file=="Image_36.jpg") 
        || and(folder=="cucumber", file=="Image_58.jpg") 
        || and(folder=="eggplant", file=="Image_56.jpg") 
        || and(folder=="jalepeno", file=="Image_38.jpg") 
        || and(folder=="jalepeno", file=="Image_61.jpg") 
        || and(folder=="onion", file=="Image_52.jpg") 
        || and(folder=="tomato", file=="Image_43.jpg") 
        || and(folder=="tomato", file=="Image_81.jpg") 
        || and(folder=="turnip", file=="Image_43.jpg")) {
      next
    }
    # Getting vector of labels
    img_label <- file
    img_path <- paste(folder_path,"/", img_label, sep="")
    test_labels <- c(test_labels, folder)
    
    # vectorize images as 28x28
    img <- image_read(img_path)
    thmb <- image_scale(img, "28x28!")# resize(jpg, size_x=28, size_y=28)
    
    png <- image_convert(thmb, format = "png", colorspace = "gray")
    raster <- as.raster(png)
    v <- as.vector(raster)
    
    v_num <- c()
    for (i in 1:784) {
      rgb.array <- col2rgb(v[i])
      v_num <- c(v_num, rgb.array[1])
    }
    v_num <- matrix(v_num,nrow=28,byrow=TRUE)
    test_images <- abind(test_images, v_num/255, along = 1)
  }
}

test_images <- test_images[-1,,]
dim(test_images)
length(test_labels)
```

```{r}
# Train Labels as numbers, apple=0, banana=1, etc
num_train_labels <- array(data = 0, dim = c(1))
class_names <- c()

last_name = ""
current_num = -1

for (name in train_labels) {
  if (name != last_name) {
    class_names <- c(class_names, name)
    last_name=name
    current_num = current_num+1
  }
  num_train_labels <- abind(num_train_labels, current_num, along = 1)
}

num_train_labels <- num_train_labels[-1]
dim(num_train_labels)


# Test Labels
num_test_labels <- array(data = 0, dim = c(1))

last_name = ""
current_num = -1

for (name in test_labels) {
  if (name != last_name) {
    last_name=name
    current_num = current_num+1
  }
  num_test_labels <- abind(num_test_labels, current_num, along = 1)
}

num_test_labels <- num_test_labels[-1]
dim(num_test_labels)
```

# View Some Images in Training Set

```{r}
image_1 <- as.data.frame(train_images[1, , ])
colnames(image_1) <- seq_len(ncol(image_1))
image_1$y <- seq_len(nrow(image_1))
image_1 <- gather(image_1, "x", "value", -y)
image_1$x <- as.integer(image_1$x)

ggplot(image_1, aes(x = x, y = y, fill = value)) +
  geom_tile() +
  scale_fill_gradient(low = "white", high = "black", na.value = NA) +
  scale_y_reverse() +
  theme_minimal() +
  theme(panel.grid = element_blank())   +
  theme(aspect.ratio = 1) +
  xlab("") +
  ylab("")
```


```{r}
par(mfcol=c(5,5))
par(mar=c(0, 0, 1.5, 0), xaxs='i', yaxs='i')
for (i in 1:25) { 
  img <- train_images[i, , ]
  name <- train_labels[i]
  img <- t(apply(img, 2, rev)) 
  image(1:28, 1:28, img, col = gray((0:255)/255), xaxt = 'n', yaxt = 'n',
        main = paste(name))
}
```

# Build the Model

```{r}
model <- keras_model_sequential()
model %>%
  layer_flatten(input_shape = c(28, 28)) %>%
  layer_dense(units = 128, activation = 'relu') %>%
  layer_dense(units = 36, activation = 'softmax')
```

```{r}
model %>% compile(
  optimizer = 'adam', 
  loss = 'sparse_categorical_crossentropy',
  metrics = c('accuracy')
)
```

```{r}
# store as history for visualization
history <- model %>% fit(train_images, num_train_labels, epochs = 1500, verbose = 0)
```

```{r}
scoretrain <- model %>% evaluate(train_images, num_train_labels, verbose = 0)
cat('Training loss:', scoretrain[1], "\n")
cat('Train accuracy:', scoretrain[2], "\n")
```

```{r}
score <- model %>% evaluate(test_images, num_test_labels, verbose = 0)

cat('Test loss:', score[1], "\n")
cat('Test accuracy:', score[2], "\n")
```

```{r}
plot(history)
```

# Making Predictions on the Test Set

```{r}
predictions <- model %>% predict(test_images)
```

## Look at Image 3 Predictions

```{r}
predictions[3, ]
```

```{r}
which.max(predictions[3, ])
max(predictions[3, ])
```

```{r}
num_test_labels[3]
test_labels[3]
```

## Graph a few predictions 

```{r}
# Plot of 25 images with predicted labels and correct labels
par(mfcol=c(5,5))
par(mar=c(0, 0, 1.5, 0), xaxs='i', yaxs='i')
for (i in 2:26) { 
  img <- test_images[i, , ]
  img <- t(apply(img, 2, rev)) 
  # subtract 1 as labels go from 0 to 9
  predicted_label <- which.max(predictions[i, ]) - 1
  true_label <- num_test_labels[i]
  if (predicted_label == true_label) {
    color <- '#008800' 
  } else {
    color <- '#bb0000'
  }
  image(1:28, 1:28, img, col = gray((0:255)/255), xaxt = 'n', yaxt = 'n',
        main = paste0(class_names[predicted_label + 1], " (",
                      class_names[true_label + 1], ")"),
        col.main = color)
}
```


# Select a Single Image and Predict

```{r}
# Grab an image from the test dataset
num = 100 # or use sample(1:359, 1)
img <- test_images[num, , , drop = FALSE]
num_test_labels[num]
test_labels[num]
```

```{r}
predictions <- model %>% predict(img)
predictions
```

```{r}
image_1 <- as.data.frame(test_images[num, , ])
colnames(image_1) <- seq_len(ncol(image_1))
image_1$y <- seq_len(nrow(image_1))
image_1 <- gather(image_1, "x", "value", -y)
image_1$x <- as.integer(image_1$x)

ggplot(image_1, aes(x = x, y = y, fill = value)) +
  geom_tile() +
  scale_fill_gradient(low = "white", high = "black", na.value = NA) +
  scale_y_reverse() +
  theme_minimal() +
  theme(panel.grid = element_blank())   +
  theme(aspect.ratio = 1) +
  xlab("") +
  ylab("")

# subtract 1, labels are 0-based
prediction <- predictions[1, ] - 1
which.max(prediction)

cat('The precicted class for Test Image 1 is', class_names[which.max(prediction)], "\n") 
```
